# Generated by Django 3.0.8 on 2020-07-13 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Without Name', max_length=50)),
                ('category', models.CharField(default='STANDARD', max_length=50)),
                ('item_type', models.CharField(default='UNIQUE', max_length=50)),
                ('description', models.CharField(default='Without Description', max_length=1000)),
                ('attributes', models.CharField(default='NONE', max_length=50)),
                ('consume_mp', models.IntegerField(default=0)),
                ('consume_heart', models.IntegerField(default=0)),
                ('statistics_hp', models.IntegerField(default=0)),
                ('statistics_mp', models.IntegerField(default=0)),
                ('statistics_heart', models.IntegerField(default=0)),
                ('statistics_str', models.IntegerField(default=0)),
                ('statistics_att', models.IntegerField(default=0)),
                ('statistics_gold', models.IntegerField(default=0)),
                ('statistics_con', models.IntegerField(default=0)),
                ('statistics_def', models.IntegerField(default=0)),
                ('statistics_max_ht', models.IntegerField(default=0)),
                ('statistics_int', models.IntegerField(default=0)),
                ('statistics_lck', models.IntegerField(default=0)),
                ('statistics_max_hp', models.IntegerField(default=0)),
                ('sell', models.FloatField(default=0.0)),
                ('found_at', models.CharField(default='NONE', max_length=100)),
                ('dropped_by', models.CharField(default='NONE', max_length=100)),
                ('effect', models.CharField(default='Without Effect', max_length=1000)),
                ('image', models.ImageField(default='Without Image', upload_to='')),
                ('animation', models.ImageField(default='Without Animation', upload_to='')),
                ('special_animation', models.ImageField(default='Without Special Animation', upload_to='')),
            ],
        ),
    ]
