# Generated by Django 3.0.8 on 2020-07-13 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='animation',
            field=models.ImageField(default='Without Animation', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.CharField(blank=True, default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='consume_heart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='consume_mp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='Without Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='dropped_by',
            field=models.CharField(blank=True, default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect',
            field=models.CharField(blank=True, default='Without Effect', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='found_at',
            field=models.CharField(blank=True, default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Without Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, default='UNIQUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='Without Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_animation',
            field=models.ImageField(default='Without Special Animation', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_att',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_con',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_def',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_gold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_heart',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_hp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_int',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_lck',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_max_hp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_max_ht',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_mp',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='statistics_str',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
