# Generated by Django 3.0.8 on 2020-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200714_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='animation',
            field=models.ImageField(default='Without Animation', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Without Image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_animation',
            field=models.ImageField(default='Without Special Animation', null=True, upload_to=''),
        ),
    ]
