# Generated by Django 3.0.8 on 2020-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200714_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='animation',
            field=models.CharField(default='Without Animation', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(default='Without Image', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_animation',
            field=models.CharField(default='Without Special Animation', max_length=5000, null=True),
        ),
    ]
